version: "3.8"

services:
  kafka:
    image: apache/kafka:4.3.0
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    healthcheck:
      test:
        [
          "CMD",
          "/opt/kafka/bin/kafka-topics.sh",
          "--bootstrap-server",
          "localhost:9092",
          "--list",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  kafka-init:
    image: apache/kafka:4.3.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "/opt/kafka/bin/kafka-topics.sh --create --if-not-exists
      --bootstrap-server kafka:9092
      --topic trending_raw
      --partitions 1
      --replication-factor 1 && echo 'Topic creado.'"

  extractor:
    build: ./extractor
    volumes:
      - ./extractor:/app
    depends_on:
      kafka:
        condition: service_healthy

  spark-streaming:
    build: ./spark
    volumes:
      - ./spark:/app
    depends_on:
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  dashboard:
    build: ./dashboard
    volumes:
      - ./dashboard:/app
    ports:
      - "8501:8501"
    depends_on:
      - redis
